### ISSUE TITLE
In line 543 at the arithmetic.tex file, seems a typo here.

### ISSUE THREAD

**Issue by m-final** [vdumoulin/conv_arithmetic#1]
Hi, Dumoulin,

Thanks for your beautiful work first.

Seems I found a small typo inside the tex file.

In 543 line at the .tex file, inside the bracket, that's the original content: 

> To factor in zero padding (i.e., only restricting to $s = 0$),

I think the idea you want to show should be s = 1, either consider about the practical moving or the relationship below:

> For any $i$, $k$ and $p$, and for $s = 1$,

Wish it is correct.

**Comment by vdumoulin** [comment]
You're absolutely right, there was a typo there. Thanks for pointing it out! It's been fixed by bde2e5c.
