### ISSUE TITLE
Ask for permission of reuse your figure

### ISSUE THREAD

**Issue by kangmiao15** [vdumoulin/conv_arithmetic#10]
@vdumoulin Thanks for your great job.Could I use a figure of deconvolution in your guide directly in my paper with a citation?

**Comment by ahundt** [comment]
@kangmiao15 The license file grants you permission, as long as you follow the terms of that agreement https://github.com/vdumoulin/conv_arithmetic/blob/master/LICENSE

**Comment by kangmiao15** [comment]
Thank you so much!
