### ISSUE TITLE
Seems a mistake on the animation of "Padding, strides, transposed (odd)"?

### ISSUE THREAD

**Issue by yehangjun** [vdumoulin/conv_arithmetic#11]
Thanks for the beautiful work first!

It seems to me that there a mistake on the animation of "Padding, strides, transposed (odd)" but I might be wrong. Looks it should have two lines of padding at the bottom right and one line of padding at the upper left, not the vice verse?

**Comment by vdumoulin** [comment]
You are correct, this is a mistake which we will fix in the upcoming update to the guide. Thank you for pointing it out!
