### ISSUE TITLE
how about the stride 2 kernel=2 deconvlution animations ?

### ISSUE THREAD

**Issue by victorygogogo** [vdumoulin/conv_arithmetic#15]

**Comment by victorygogogo** [comment]
@dwf 

how about the stride 2 kernel=2 deconvlution animations ?

**Comment by dwf** [comment]
Not sure why you're tagging me, this isn't my project.

**Comment by victorygogogo** [comment]
@dwf  I am sorry.

@vdumoulin 
@fvisin 
how about the stride 2 kernel=2 deconvlution animations ?

**Comment by fvisin** [comment]
Hello @victorygogogo ,

unfortunately we don't have time to add more material to the guide, but the code is there for you to play with if you want to draw more animations.
