### ISSUE TITLE
Section 4.6

### ISSUE THREAD

**Issue by dwf** [vdumoulin/conv_arithmetic#2]
i' with a tilde is described but then i' is used in relationship 13.

**Comment by dwf** [comment]
Yeah, the equation for o should use i, not i'. And you probably want to lose the tildes too.

**Comment by vdumoulin** [comment]
We use the tildes to differentiate the direct convolution view of the transposed convolution from the transposed convolution view itself.

I'm pretty sure the equation in relationship 13 is correct (you can verify that by solving the equation in relationship 6 for `i`, which corresponds to `o'` in the transposed convolution case), but we could maybe make that clearer by making use of relationship 2 on the direct convolution view:

```
\tilde{i}' = i' + (s - 1)(i' - 1),
        o' = (\tilde{i}' - k') + 2p' + 1
           = (i' + (s - 1)(i' - 1) - k) + 2(k - p - 1) + 1
           = s(i' - 1) + k - 2p
```

**Comment by dwf** [comment]
If i' contains a multiplication by s then you have an s^2 term in there, don't you?

**Comment by vdumoulin** [comment]
I'm not sure I understand what you mean.

**Comment by dwf** [comment]
What exactly is i' in this situation? I see only tilde-i'.

**Comment by vdumoulin** [comment]
`i'` corresponds to the input size of the transposed convolution or, alternatively, the output size of the converse convolution.
