### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by jeremy-rutman** [vdumoulin/conv_arithmetic#20]
I hit the following make error after downloading and doing ./bin/generate_makefile 
```
jeremy@jeremy-TECRA-Z40-C:~conv_arithmetic$ make all_animations
./bin/produce_figure arithmetic no_padding_no_strides 0 --input-size=4 --output-size=2 --padding=0 --kernel-size=3 --stride=1 
Traceback (most recent call last):
  File "./bin/produce_figure", line 272, in <module>
    compile_figure(which_, name, step, **args_dict)
  File "./bin/produce_figure", line 223, in compile_figure
    if '! LaTeX Error' in stdoutdata or '! Emergency stop' in stdoutdata:
TypeError: a bytes-like object is required, not 'str'
Makefile:98: recipe for target 'pdf/no_padding_no_strides_00.pdf' failed
make: *** [pdf/no_padding_no_strides_00.pdf] Error 1
```
makefile looks like 

```
conv_arithmetic.pdf : export BSTINPUTS=$BSTINPUTS:./natbib
conv_arithmetic.pdf : conv_arithmetic.tex
	pdflatex conv_arithmetic
	pdflatex conv_arithmetic
	bibtex conv_arithmetic
	pdflatex conv_arithmetic
	pdflatex conv_arithmetic

.PHONY : clean
clean : 
	rm -f conv_arithmetic.{aux,bbl,blg,log}

.PHONY : all_animations
all_animations : gif/no_padding_no_strides.gif gif/no_padding_no_strides_transposed.gif gif/arbitrary_padding_no_strides.gif gif/arbitrary_padding_no_strides_transposed.gif
 gif/same_padding_no_strides.gif gif/same_padding_no_strides_transposed.gif gif/full_padding_no_strides.gif gif/full_padding_no_strides_transposed.gif gif/no_padding_stride
s.gif gif/no_padding_strides_transposed.gif gif/padding_strides.gif gif/padding_strides_transposed.gif gif/padding_strides_odd.gif gif/padding_strides_odd_transposed.gif gi
f/dilation.gif gif/numerical_no_padding_no_strides.gif gif/numerical_padding_strides.gif gif/numerical_average_pooling.gif gif/numerical_max_pooling.gif

.SECONDARY : 

gif/no_padding_no_strides.gif : png/no_padding_no_strides_00.png png/no_padding_no_strides_01.png png/no_padding_no_strides_02.png png/no_padding_no_strides_03.png
	convert -delay 100 -loop 0 -layers Optimize +map -dispose previous $^ $@
	gifsicle --batch -O3 $@

gif/no_padding_no_strides_transposed.gif : png/no_padding_no_strides_transposed_00.png png/no_padding_no_strides_transposed_01.png png/no_padding_no_strides_transposed_02.p
ng png/no_padding_no_strides_transposed_03.png png/no_padding_no_strides_transposed_04.png png/no_padding_no_strides_transposed_05.png png/no_padding_no_strides_transposed_
06.png png/no_padding_no_strides_transposed_07.png png/no_padding_no_strides_transposed_08.png png/no_padding_no_strides_transposed_09.png png/no_padding_no_strides_transpo
sed_10.png png/no_padding_no_strides_transposed_11.png png/no_padding_no_strides_transposed_12.png png/no_padding_no_strides_transposed_13.png png/no_padding_no_strides_tra
nsposed_14.png png/no_padding_no_strides_transposed_15.png
	convert -delay 100 -loop 0 -layers Optimize +map -dispose previous $^ $@
	gifsicle --batch -O3 $@

gif/arbitrary_padding_no_strides.gif : png/arbitrary_padding_no_strides_00.png png/arbitrary_padding_no_strides_01.png png/arbitrary_padding_no_strides_02.png png/arbitrary
_padding_no_strides_03.png png/arbitrary_padding_no_strides_04.png png/arbitrary_padding_no_strides_05.png png/arbitrary_padding_no_strides_06.png png/arbitrary_padding_no_
strides_07.png png/arbitrary_padding_no_strides_08.png png/arbitrary_padding_no_strides_09.png png/arbitrary_padding_no_strides_10.png png/arbitrary_padding_no_strides_11.p
ng png/arbitrary_padding_no_strides_12.png png/arbitrary_padding_no_strides_13.png png/arbitrary_padding_no_strides_14.png png/arbitrary_padding_no_strides_15.png png/arbit
rary_padding_no_strides_16.png png/arbitrary_padding_no_strides_17.png png/arbitrary_padding_no_strides_18.png png/arbitrary_padding_no_strides_19.png png/arbitrary_padding
_no_strides_20.png png/arbitrary_padding_no_strides_21.png png/arbitrary_padding_no_strides_22.png png/arbitrary_padding_no_strides_23.png png/arbitrary_padding_no_strides_
24.png png/arbitrary_padding_no_strides_25.png png/arbitrary_padding_no_strides_26.png png/arbitrary_padding_no_strides_27.png png/arbitrary_padding_no_strides_28.png png/a
rbitrary_padding_no_strides_29.png png/arbitrary_padding_no_strides_30.png png/arbitrary_padding_no_strides_31.png png/arbitrary_padding_no_strides_32.png png/arbitrary_pad

```

....etc

**Comment by fvisin** [comment]
I am sorry but we cannot really provide support for this kind of errors as they are system / configuration dependent. There should be a more complete log in `pdf/jobname.log`, I hope that can be of help to understand the cause of the error!

**Comment by xiaozhang8tuo** [comment]
> I hit the following make error after downloading and doing ./bin/generate_makefile
> 
> ```
> jeremy@jeremy-TECRA-Z40-C:~conv_arithmetic$ make all_animations
> ./bin/produce_figure arithmetic no_padding_no_strides 0 --input-size=4 --output-size=2 --padding=0 --kernel-size=3 --stride=1 
> Traceback (most recent call last):
>   File "./bin/produce_figure", line 272, in <module>
>     compile_figure(which_, name, step, **args_dict)
>   File "./bin/produce_figure", line 223, in compile_figure
>     if '! LaTeX Error' in stdoutdata or '! Emergency stop' in stdoutdata:
> TypeError: a bytes-like object is required, not 'str'
> Makefile:98: recipe for target 'pdf/no_padding_no_strides_00.pdf' failed
> make: *** [pdf/no_padding_no_strides_00.pdf] Error 1
> ```
> 
> makefile looks like
> 
> ```
> conv_arithmetic.pdf : export BSTINPUTS=$BSTINPUTS:./natbib
> conv_arithmetic.pdf : conv_arithmetic.tex
> 	pdflatex conv_arithmetic
> 	pdflatex conv_arithmetic
> 	bibtex conv_arithmetic
> 	pdflatex conv_arithmetic
> 	pdflatex conv_arithmetic
> 
> .PHONY : clean
> clean : 
> 	rm -f conv_arithmetic.{aux,bbl,blg,log}
> 
> .PHONY : all_animations
> all_animations : gif/no_padding_no_strides.gif gif/no_padding_no_strides_transposed.gif gif/arbitrary_padding_no_strides.gif gif/arbitrary_padding_no_strides_transposed.gif
>  gif/same_padding_no_strides.gif gif/same_padding_no_strides_transposed.gif gif/full_padding_no_strides.gif gif/full_padding_no_strides_transposed.gif gif/no_padding_stride
> s.gif gif/no_padding_strides_transposed.gif gif/padding_strides.gif gif/padding_strides_transposed.gif gif/padding_strides_odd.gif gif/padding_strides_odd_transposed.gif gi
> f/dilation.gif gif/numerical_no_padding_no_strides.gif gif/numerical_padding_strides.gif gif/numerical_average_pooling.gif gif/numerical_max_pooling.gif
> 
> .SECONDARY : 
> 
> gif/no_padding_no_strides.gif : png/no_padding_no_strides_00.png png/no_padding_no_strides_01.png png/no_padding_no_strides_02.png png/no_padding_no_strides_03.png
> 	convert -delay 100 -loop 0 -layers Optimize +map -dispose previous $^ $@
> 	gifsicle --batch -O3 $@
> 
> gif/no_padding_no_strides_transposed.gif : png/no_padding_no_strides_transposed_00.png png/no_padding_no_strides_transposed_01.png png/no_padding_no_strides_transposed_02.p
> ng png/no_padding_no_strides_transposed_03.png png/no_padding_no_strides_transposed_04.png png/no_padding_no_strides_transposed_05.png png/no_padding_no_strides_transposed_
> 06.png png/no_padding_no_strides_transposed_07.png png/no_padding_no_strides_transposed_08.png png/no_padding_no_strides_transposed_09.png png/no_padding_no_strides_transpo
> sed_10.png png/no_padding_no_strides_transposed_11.png png/no_padding_no_strides_transposed_12.png png/no_padding_no_strides_transposed_13.png png/no_padding_no_strides_tra
> nsposed_14.png png/no_padding_no_strides_transposed_15.png
> 	convert -delay 100 -loop 0 -layers Optimize +map -dispose previous $^ $@
> 	gifsicle --batch -O3 $@
> 
> gif/arbitrary_padding_no_strides.gif : png/arbitrary_padding_no_strides_00.png png/arbitrary_padding_no_strides_01.png png/arbitrary_padding_no_strides_02.png png/arbitrary
> _padding_no_strides_03.png png/arbitrary_padding_no_strides_04.png png/arbitrary_padding_no_strides_05.png png/arbitrary_padding_no_strides_06.png png/arbitrary_padding_no_
> strides_07.png png/arbitrary_padding_no_strides_08.png png/arbitrary_padding_no_strides_09.png png/arbitrary_padding_no_strides_10.png png/arbitrary_padding_no_strides_11.p
> ng png/arbitrary_padding_no_strides_12.png png/arbitrary_padding_no_strides_13.png png/arbitrary_padding_no_strides_14.png png/arbitrary_padding_no_strides_15.png png/arbit
> rary_padding_no_strides_16.png png/arbitrary_padding_no_strides_17.png png/arbitrary_padding_no_strides_18.png png/arbitrary_padding_no_strides_19.png png/arbitrary_padding
> _no_strides_20.png png/arbitrary_padding_no_strides_21.png png/arbitrary_padding_no_strides_22.png png/arbitrary_padding_no_strides_23.png png/arbitrary_padding_no_strides_
> 24.png png/arbitrary_padding_no_strides_25.png png/arbitrary_padding_no_strides_26.png png/arbitrary_padding_no_strides_27.png png/arbitrary_padding_no_strides_28.png png/a
> rbitrary_padding_no_strides_29.png png/arbitrary_padding_no_strides_30.png png/arbitrary_padding_no_strides_31.png png/arbitrary_padding_no_strides_32.png png/arbitrary_pad
> ```
> 
> ....etc

hava you solved this problem ? my friend

**Comment by TheGreatGalaxy** [comment]
> > I hit the following make error after downloading and doing ./bin/generate_makefile
> > ```
> > jeremy@jeremy-TECRA-Z40-C:~conv_arithmetic$ make all_animations
> > ./bin/produce_figure arithmetic no_padding_no_strides 0 --input-size=4 --output-size=2 --padding=0 --kernel-size=3 --stride=1 
> > Traceback (most recent call last):
> >   File "./bin/produce_figure", line 272, in <module>
> >     compile_figure(which_, name, step, **args_dict)
> >   File "./bin/produce_figure", line 223, in compile_figure
> >     if '! LaTeX Error' in stdoutdata or '! Emergency stop' in stdoutdata:
> > TypeError: a bytes-like object is required, not 'str'
> > Makefile:98: recipe for target 'pdf/no_padding_no_strides_00.pdf' failed
> > make: *** [pdf/no_padding_no_strides_00.pdf] Error 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > makefile looks like
> > ```
> > conv_arithmetic.pdf : export BSTINPUTS=$BSTINPUTS:./natbib
> > conv_arithmetic.pdf : conv_arithmetic.tex
> > 	pdflatex conv_arithmetic
> > 	pdflatex conv_arithmetic
> > 	bibtex conv_arithmetic
> > 	pdflatex conv_arithmetic
> > 	pdflatex conv_arithmetic
> > 
> > .PHONY : clean
> > clean : 
> > 	rm -f conv_arithmetic.{aux,bbl,blg,log}
> > 
> > .PHONY : all_animations
> > all_animations : gif/no_padding_no_strides.gif gif/no_padding_no_strides_transposed.gif gif/arbitrary_padding_no_strides.gif gif/arbitrary_padding_no_strides_transposed.gif
> >  gif/same_padding_no_strides.gif gif/same_padding_no_strides_transposed.gif gif/full_padding_no_strides.gif gif/full_padding_no_strides_transposed.gif gif/no_padding_stride
> > s.gif gif/no_padding_strides_transposed.gif gif/padding_strides.gif gif/padding_strides_transposed.gif gif/padding_strides_odd.gif gif/padding_strides_odd_transposed.gif gi
> > f/dilation.gif gif/numerical_no_padding_no_strides.gif gif/numerical_padding_strides.gif gif/numerical_average_pooling.gif gif/numerical_max_pooling.gif
> > 
> > .SECONDARY : 
> > 
> > gif/no_padding_no_strides.gif : png/no_padding_no_strides_00.png png/no_padding_no_strides_01.png png/no_padding_no_strides_02.png png/no_padding_no_strides_03.png
> > 	convert -delay 100 -loop 0 -layers Optimize +map -dispose previous $^ $@
> > 	gifsicle --batch -O3 $@
> > 
> > gif/no_padding_no_strides_transposed.gif : png/no_padding_no_strides_transposed_00.png png/no_padding_no_strides_transposed_01.png png/no_padding_no_strides_transposed_02.p
> > ng png/no_padding_no_strides_transposed_03.png png/no_padding_no_strides_transposed_04.png png/no_padding_no_strides_transposed_05.png png/no_padding_no_strides_transposed_
> > 06.png png/no_padding_no_strides_transposed_07.png png/no_padding_no_strides_transposed_08.png png/no_padding_no_strides_transposed_09.png png/no_padding_no_strides_transpo
> > sed_10.png png/no_padding_no_strides_transposed_11.png png/no_padding_no_strides_transposed_12.png png/no_padding_no_strides_transposed_13.png png/no_padding_no_strides_tra
> > nsposed_14.png png/no_padding_no_strides_transposed_15.png
> > 	convert -delay 100 -loop 0 -layers Optimize +map -dispose previous $^ $@
> > 	gifsicle --batch -O3 $@
> > 
> > gif/arbitrary_padding_no_strides.gif : png/arbitrary_padding_no_strides_00.png png/arbitrary_padding_no_strides_01.png png/arbitrary_padding_no_strides_02.png png/arbitrary
> > _padding_no_strides_03.png png/arbitrary_padding_no_strides_04.png png/arbitrary_padding_no_strides_05.png png/arbitrary_padding_no_strides_06.png png/arbitrary_padding_no_
> > strides_07.png png/arbitrary_padding_no_strides_08.png png/arbitrary_padding_no_strides_09.png png/arbitrary_padding_no_strides_10.png png/arbitrary_padding_no_strides_11.p
> > ng png/arbitrary_padding_no_strides_12.png png/arbitrary_padding_no_strides_13.png png/arbitrary_padding_no_strides_14.png png/arbitrary_padding_no_strides_15.png png/arbit
> > rary_padding_no_strides_16.png png/arbitrary_padding_no_strides_17.png png/arbitrary_padding_no_strides_18.png png/arbitrary_padding_no_strides_19.png png/arbitrary_padding
> > _no_strides_20.png png/arbitrary_padding_no_strides_21.png png/arbitrary_padding_no_strides_22.png png/arbitrary_padding_no_strides_23.png png/arbitrary_padding_no_strides_
> > 24.png png/arbitrary_padding_no_strides_25.png png/arbitrary_padding_no_strides_26.png png/arbitrary_padding_no_strides_27.png png/arbitrary_padding_no_strides_28.png png/a
> > rbitrary_padding_no_strides_29.png png/arbitrary_padding_no_strides_30.png png/arbitrary_padding_no_strides_31.png png/arbitrary_padding_no_strides_32.png png/arbitrary_pad
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ....etc
> 
> hava you solved this problem ? my friend

I think maybe youcan try:
"sudo apt install doxygen-latex"

**Comment by TheGreatGalaxy** [comment]
And should do
1. sudo apt install gifsicle
2. modify /etc/ImageMagick-6/policy.xml
root@Lian:~/# vim /etc/ImageMagick-6/policy.xml
 
change the follwing line: 
'''\<policy domain="coder" rights="none" pattern="PDF" />'''
into:
'''\<policy domain="coder" rights="read|write" pattern="PDF" />'''
then, add the following line:
'''\<policy domain="coder" rights="read|write" pattern="LABEL" />'''

**Comment by TheGreatGalaxy** [comment]
And should do
1. sudo apt install gifsicle
2. modify /etc/ImageMagick-6/policy.xml
root@Lian:~/# vim /etc/ImageMagick-6/policy.xml
 
change the follwing line: 
<policy domain="coder" rights="none" pattern="PDF" />
into:
<policy domain="coder" rights="read|write" pattern="PDF" />
then, add the following line:
<policy domain="coder" rights="read|write" pattern="LABEL" />

**Comment by fvisin** [comment]
Actually, the error is due to the fact that the code is written in python2 and you seem to be running it with python3. Unfortunately this is legacy code now and we don't have the time to port it to python3, but if you want to give it a try I'm happy to review a PR.
