### ISSUE TITLE
Partial Convolutions

### ISSUE THREAD

**Issue by anantzoid** [vdumoulin/conv_arithmetic#21]
It'd be great if there's also a gif of  [Partial Convolutions](https://arxiv.org/abs/1804.07723) in the near future.
Thanks!

**Comment by fvisin** [comment]
Hi @anantzoid ,

thank you for your suggestion. Unfortunately I don't think Vincent and I have cycles to add more information to the guide, but if you or someone else is willing to extend the source code to include partial convolutions we'd be happy to accept a PR!
