### ISSUE TITLE
Misleading README license statement

### ISSUE THREAD

**Issue by justinpinkney** [vdumoulin/conv_arithmetic#22]
The line, "The code and/or the images of this tutorial are free to use for non-commercial purposes with proper attribution:" in the README suggests that the same is not true for commercial purposes, but the MIT license permits commercial use.

**Comment by endolith** [comment]
Yep, I saw these in [Theano documentation](http://deeplearning.net/software/theano_versions/dev/tutorial/conv_arithmetic.html) and thought they would be [useful in Wikipedia](https://commons.wikimedia.org/wiki/Category:Convolution), and tried to find the license.  

Theano is BSD-3, which allows commercial use and [is compatible with Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:Expat/MIT_License), but if this repo is the original source, and it bans commercial use, then that's not compatible with either Theano's license or Wikimedia's (or [its own LICENSE file](https://github.com/vdumoulin/conv_arithmetic/blob/master/LICENSE)).

![2019-04-12 11_35_16-conv_arithmetic_LICENSE at master · vdumoulin_conv_arithmetic - Waterfox](https://user-images.githubusercontent.com/58611/56049305-2fdaa500-5d17-11e9-8926-89988389e967.png)

**Comment by fvisin** [comment]
Apologies for taking so long to address this issue and thank you for pointing it out. I amended the readme to be compatible with the license. Feel free to use the code / images with proper attribution. Thank you!
