### ISSUE TITLE
Cyan?

### ISSUE THREAD

**Issue by sharvil** [vdumoulin/conv_arithmetic#24]
The text says the feature maps are cyan and blue but the images show feature maps that are green and blue.

**Comment by fvisin** [comment]
Your perplexity probably derives from cyan being a greenish-blue color:
https://en.wikipedia.org/wiki/Cyan

Of the two, the cyan feature maps are those that have more of a greenish look.

**Comment by sharvil** [comment]
Thanks for the clarification. I think I was trying to convey that describing one of the colors as cyan can be ambiguous precisely because cyan is defined as a greenish-blue. Maybe it's clearer to describe one as green and the other as blue in the readme. In any case, it's just a minor suggestion.
