### ISSUE TITLE
Convolution algorithm

### ISSUE THREAD

**Issue by tonbing** [vdumoulin/conv_arithmetic#26]
I understand your algorithm and implementation for 2d convolution using shift register based concept. Do you think this concept can be applied for 3d convolution ?

**Comment by fvisin** [comment]
The concepts explained in this tutorial (stride, padding, ..) are not specific to 2D convolutions and can be directly applied to higher dimensional convolutions. Similarly, the code could in principle be extended to cover 3D convolutions. This goes beyond the scope of this guide though, as it would make it much more complicated without adding much information.
