### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by Arithmeticjia** [vdumoulin/conv_arithmetic#28]
when i try to  do "make all_animations"  from the repository's root directory,
there is an error
(env_shan) Arithmetic@qingjiaowosuanshujiadeMacBook-Pro conv_arithmetic-master % make all_animations
convert -density 600 pdf/numerical_no_padding_no_strides_00.pdf -flatten -resize 25% png/numerical_no_padding_no_strides_00.png
make: convert: No such file or directory
make: *** [png/numerical_no_padding_no_strides_00.png] Error 1

the readme can't help me ,is there any one can fix it or give me some advice?
thx

**Comment by laisimiao** [comment]
i also have this problem. Have you solved it?

**Comment by theevann** [comment]
See https://stackoverflow.com/questions/28627473/error-for-convert-command-in-command-line

On ubuntu:
```shell
sudo apt-get install imagemagick
```
