### ISSUE TITLE
Release arXiv version v2

### ISSUE THREAD

**Issue by Jakobovski** [vdumoulin/conv_arithmetic#3]
Thanks for making this great guide! Its very useful and well written. 

I am not sure if this is an error in the guide or a misunderstanding on my part.

Figures 2.1 through 2.4 are described as having "no stride" but then in the same sentence are described as having "unit strides" . It seems to me that "no stride" is not equivalent to "unit stride". IE:  "no stride" should mean `s=0` rather than `s=1`.  

See image below.

![image](https://cloud.githubusercontent.com/assets/2724082/15040349/b484c6f8-12bc-11e6-9c20-c0bcc9fd1e61.png)

**Comment by vdumoulin** [comment]
I agree with you, mixing the terms _no strides_ and _unit strides_ makes it more confusing than necessary. A fix has already been pushed on the repo (f9fabd7), but we haven't put out an updated version of the guide on arXiv yet.

If it's okay with you, I'll change the issue to remind us to push a new version on arXiv soon.

**Comment by Jakobovski** [comment]
👍
