### ISSUE TITLE
The transposed convolutional animation is confusing

### ISSUE THREAD

**Issue by sicongzhao** [vdumoulin/conv_arithmetic#30]
I feel like the input and output could be mislabeled in transposed convolutional animation section.

**Comment by fvisin** [comment]
They seem correct to me. Blue maps (below) are inputs, and cyan maps (above) are outputs.

**Comment by DongHwanJang** [comment]
According to the paper, it states that 4x4 cyan feature is an input, rather than output.
Could you explain why blue maps are input in this case?
![image](https://user-images.githubusercontent.com/30042447/152905471-fac9fdb9-eab0-4cc3-b11e-4b19244ea3f4.png)
